class Forex
  class_attribute :symbols
  #self.symbols =  [ 'USAUDUSD','USDINIW','USEURUSD','USGBPUSD','USNZDUSD','USUSDCAD','USUSDCHF','USUSDCNY','USUSDHKD','USUSDJPY','USUSDMOP','USUSDMYR','USUSDSGD','USUSDTWD']
  self.symbols =  [ 'USAUDUSD', 'USEURUSD','USGBPUSD','USNZDUSD','USUSDCAD' ,'USUSDCNY','USUSDHKD','USUSDJPY','USUSDMOP','USUSDMYR','USUSDSGD']

end
